name: analyse

on:
  push:
    branches:
      - main

jobs:


  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: stable
            flutter-version: 3.19.0
      - run: dart --version
      - run: flutter --version    
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
